---

- name: Create OpenStack Instances
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Include Instance variables
      include_vars: instances.yml

    - name: Create Instance
      openstack.cloud.server:
        cloud:   
          2881-project:
            auth:
              auth_url: "https://api.orange.sc01.infra.opentlc.com:13000//v3"
              username: "2881-user"
              project_name: "2881-project"
              project_id: "14861e22e0cc44419920fe9c154b0e73"
              user_domain_name: "Default"
              password: "eIA3wr7Z2MK8"
            region_name: "regionOne"
            interface: "public"
            identity_api_version: 3
        name: "{{ instance.name }}"
        image: "{{ instance.image }}"
        key_name: "{{ instance.keypair }}"
        flavor: "{{ instance.flavor }}"
        security_groups: "{{ instance.security_group }}"
        delete_fip: yes
        wait: no
        nics:
          - net-name: "{{ instance.internal_network }}"
        meta: "AnsibleGroup={{instance.metadata.AnsibleGroup}},deployment_name={{instance.metadata.deployment_name}}"
      loop: "{{ instances }}"
      loop_control:
        loop_var: instance